
Skip to content
Pull requests
Issues
Marketplace
Explore
@lmoresi
ANU-RSES-Education /
SeismicNoise_AuSIS
Template

1
0

    0

Code
Issues 0
Pull requests 0
Actions
Projects 0
Wiki
Security 0
Insights

    Settings

SeismicNoise_AuSIS/.github/workflows/notebook_runner.yml
@lmoresi lmoresi Try log file once more d916dac 4 hours ago
74 lines (58 sloc) 2.06 KB
name: run notebooks

# push or on schedule
on:

  schedule: 
    - cron:  '0 17 * * *'  # Every day at 5pm UTC - early am AuSIS time 

  push: 
    
jobs:
  # This workflow contains a single job called "build"
  compute:
    name: Run notebook and upload result.
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - uses: goanpeca/setup-miniconda@v1.5.0
      with:
        auto-update-conda: true
        python-version: 3.7
        activate-environment: ausis
        environment-file: environment.yml
        auto-activate-base: false

    - name: Install dependencies with conda # (the shell line is needed for conda paths etc)
      shell: bash -l {0}
      run: |
        pip install tables
        conda info 
        conda list
        
    - name: Run the code
      shell: bash -l {0}
      run: |
        ./notebook_runner.sh &> output_log.txt
        ls -l workdir  # add this to the logs for debugging / monitoring 
        
    - name: Upload the log files (for now just an artefact)
      continue-on-error: true  
      uses: actions/upload-artifact@v1
      with:
        name: logs
        path: output_log.txt

    - name: Upload the image files 
      uses: actions/upload-artifact@v1
      with:
        name: figures-etc
        path: results
   
    - name: Commit files 
      continue-on-error: true  # Usually indicates nothing has change / nothing nees to be committed.
      run: |
        git config --local user.email "diablo@underworldcode.org"
        git config --local user.name "ProfessorDiablobot"
        git add results/*.png
        git add data/*npz 
        git add results/*.csv
        git commit -m "Updated results: `date` " 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    

      

    © 2020 GitHub, Inc.
    Terms
    Privacy
    Security
    Status
    Help

    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

